version: "3.2"
services:
    le:
        image: certbot/dns-route53
        environment:
            - AWS_ACCESS_KEY_ID=YOUR-ACCESS-KEY
            - AWS_SECRET_ACCESS_KEY=YOUR-ACCESS-SECRET
        entrypoint: certbot certonly --dns-route53 --server https://acme-v02.api.letsencrypt.org/directory --agree-tos --non-interactive --email YOUR-EMAIL -d *.YOUR-ROUTE53-DOMAIN 
        volumes:
            - "certs:/etc/letsencrypt/"
    knary:
        build: .
        restart: always
        volumes:
            - "certs:/knary/certs"
        ports:
            - "53:53"
            - "53:53/udp"
            - "80:80"
            - "443:443"
        depends_on:
            - le
volumes:
    certs:
